apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: supranerd-org-tls
spec:
  secretName: supranerd-org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: supranerd.org
  dnsNames:
    - supranerd.org
    - www.supranerd.org
