apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'patrick.haldi@mailbox.org'
    privateKeySecretRef:
      name: letsencrypt-prod
    # http01: {}
    solvers:
      - http01:
          ingress:
            class: nginx
