name: Deploy MuliK8s
on:
  push:
    branches:
      - main
env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t cygnetops/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true cygnetops/react-test npm test

      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-376810

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: europe-west1-b

      - name: Build
        run: |-
          docker build -t phygan/multi-client-k8s-gh:latest -t phygan/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t phygan/multi-server-k8s-pgfix-gh:latest -t phygan/multi-server-k8s-pgfix-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t phygan/multi-worker-k8s-gh:latest -t phygan/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push phygan/multi-client-k8s-gh:latest
          docker push phygan/multi-server-k8s-pgfix-gh:latest
          docker push phygan/multi-worker-k8s-gh:latest

          docker push phygan/multi-client-k8s-gh:${{ env.SHA }}
          docker push phygan/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          docker push phygan/multi-worker-k8s-gh:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/client-deployment my-client=phygan/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/server-deployment my-server=phygan/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment my-worker=phygan/multi-worker-k8s-gh:${{ env.SHA }}
